#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MicroBluer.AndroidCtrls.LoadingAnimation.Resource", IsApplication=false)]

namespace MicroBluer.AndroidCtrls.LoadingAnimation
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int loading_renderer = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int ic_eletric_fan = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int ic_leaf = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int ic_loading = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public static int BalloonLoadingRenderer = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int CircleBroodLoadingRenderer = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int CollisionLoadingRenderer = 2131034114;
			
			// aapt resource value: 0x7f050003
			public static int CoolWaitLoadingRenderer = 2131034115;
			
			// aapt resource value: 0x7f050004
			public static int DanceLoadingRenderer = 2131034116;
			
			// aapt resource value: 0x7f050005
			public static int DayNightLoadingRenderer = 2131034117;
			
			// aapt resource value: 0x7f050006
			public static int ElectricFanLoadingRenderer = 2131034118;
			
			// aapt resource value: 0x7f050007
			public static int FishLoadingRenderer = 2131034119;
			
			// aapt resource value: 0x7f050008
			public static int GearLoadingRenderer = 2131034120;
			
			// aapt resource value: 0x7f050009
			public static int GhostsEyeLoadingRenderer = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public static int GuardLoadingRenderer = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public static int LevelLoadingRenderer = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public static int MaterialLoadingRenderer = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public static int SwapLoadingRenderer = 2131034125;
			
			// aapt resource value: 0x7f050010
			public static int WaitingView = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public static int WaterBottleLoadingRenderer = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public static int WhorlLoadingRenderer = 2131034127;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int LoadingDialog = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public static int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingView = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public static int LoadingView_loading_renderer = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
