#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LazyWelfare.AndroidMobile.Resource", IsApplication=true)]

namespace LazyWelfare.AndroidMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Animation.listview_down = global::LazyWelfare.AndroidMobile.Resource.Animation.listview_down;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Animation.listview_fade_in = global::LazyWelfare.AndroidMobile.Resource.Animation.listview_fade_in;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Animation.listview_fade_out = global::LazyWelfare.AndroidMobile.Resource.Animation.listview_fade_out;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Animation.listview_up = global::LazyWelfare.AndroidMobile.Resource.Animation.listview_up;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Color.top_bg = global::LazyWelfare.AndroidMobile.Resource.Color.top_bg;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Drawable.gallery_back = global::LazyWelfare.AndroidMobile.Resource.Drawable.gallery_back;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Drawable.gallery_down = global::LazyWelfare.AndroidMobile.Resource.Drawable.gallery_down;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Drawable.gallery_up = global::LazyWelfare.AndroidMobile.Resource.Drawable.gallery_up;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Drawable.ic_camera = global::LazyWelfare.AndroidMobile.Resource.Drawable.ic_camera;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Drawable.image_not_exist = global::LazyWelfare.AndroidMobile.Resource.Drawable.image_not_exist;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Drawable.pick_photo_checkbox = global::LazyWelfare.AndroidMobile.Resource.Drawable.pick_photo_checkbox;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Drawable.pick_photo_checkbox_check = global::LazyWelfare.AndroidMobile.Resource.Drawable.pick_photo_checkbox_check;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Drawable.pick_photo_checkbox_normal = global::LazyWelfare.AndroidMobile.Resource.Drawable.pick_photo_checkbox_normal;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Id.btn_back = global::LazyWelfare.AndroidMobile.Resource.Id.btn_back;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Id.check = global::LazyWelfare.AndroidMobile.Resource.Id.check;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Id.commit = global::LazyWelfare.AndroidMobile.Resource.Id.commit;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Id.foldName = global::LazyWelfare.AndroidMobile.Resource.Id.foldName;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Id.gallery_tip = global::LazyWelfare.AndroidMobile.Resource.Id.gallery_tip;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Id.gridView = global::LazyWelfare.AndroidMobile.Resource.Id.gridView;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Id.listView = global::LazyWelfare.AndroidMobile.Resource.Id.listView;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Id.listViewParent = global::LazyWelfare.AndroidMobile.Resource.Id.listViewParent;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Id.photoCount = global::LazyWelfare.AndroidMobile.Resource.Id.photoCount;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Id.rl = global::LazyWelfare.AndroidMobile.Resource.Id.rl;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Id.selectFold = global::LazyWelfare.AndroidMobile.Resource.Id.selectFold;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Id.thumbnail = global::LazyWelfare.AndroidMobile.Resource.Id.thumbnail;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Id.top_layout = global::LazyWelfare.AndroidMobile.Resource.Id.top_layout;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Layout.ImageSelect = global::LazyWelfare.AndroidMobile.Resource.Layout.ImageSelect;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Layout.ImageSelect_IncludeTop = global::LazyWelfare.AndroidMobile.Resource.Layout.ImageSelect_IncludeTop;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Layout.ImageSelect_PhotoPickGridListItem = global::LazyWelfare.AndroidMobile.Resource.Layout.ImageSelect_PhotoPickGridListItem;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.Layout.ImageSelect_PhotoPickListItem = global::LazyWelfare.AndroidMobile.Resource.Layout.ImageSelect_PhotoPickListItem;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.String.app_name = global::LazyWelfare.AndroidMobile.Resource.String.app_name;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.String.l_album_name_all = global::LazyWelfare.AndroidMobile.Resource.String.l_album_name_all;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.String.l_album_name_camera = global::LazyWelfare.AndroidMobile.Resource.String.l_album_name_camera;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.String.l_album_name_download = global::LazyWelfare.AndroidMobile.Resource.String.l_album_name_download;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.String.l_album_name_screen_shot = global::LazyWelfare.AndroidMobile.Resource.String.l_album_name_screen_shot;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.String.l_album_name_selected = global::LazyWelfare.AndroidMobile.Resource.String.l_album_name_selected;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.String.l_confirm_dialog_message = global::LazyWelfare.AndroidMobile.Resource.String.l_confirm_dialog_message;
			global::LazyWelfare.AndroidMobile.ImageSelect.Resource.String.l_confirm_dialog_title = global::LazyWelfare.AndroidMobile.Resource.String.l_confirm_dialog_title;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::LazyWelfare.AndroidMobile.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::LazyWelfare.AndroidMobile.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::LazyWelfare.AndroidMobile.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int listview_down = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int listview_fade_in = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int listview_fade_out = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int listview_up = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int top_bg = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int area_above_left = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int area_above_right = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int area_below_left = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int area_below_right = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int blue_face = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int gallery_back = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int gallery_down = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int gallery_up = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_camera = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int image_not_exist = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int pick_photo_checkbox = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int pick_photo_checkbox_check = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int pick_photo_checkbox_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int scan_album = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int scan_bulb = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int splash_screen = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int splashscreen = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int btn_back = 2131230724;
			
			// aapt resource value: 0x7f08000b
			public const int check = 2131230731;
			
			// aapt resource value: 0x7f080008
			public const int commit = 2131230728;
			
			// aapt resource value: 0x7f080016
			public const int contentFrame = 2131230742;
			
			// aapt resource value: 0x7f080006
			public const int foldName = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int gallery_tip = 2131230727;
			
			// aapt resource value: 0x7f080001
			public const int gridView = 2131230721;
			
			// aapt resource value: 0x7f080011
			public const int imageAlbum = 2131230737;
			
			// aapt resource value: 0x7f080014
			public const int imageBulb = 2131230740;
			
			// aapt resource value: 0x7f08000d
			public const int imgview = 2131230733;
			
			// aapt resource value: 0x7f080003
			public const int listView = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int listViewParent = 2131230722;
			
			// aapt resource value: 0x7f08000c
			public const int photoCount = 2131230732;
			
			// aapt resource value: 0x7f080009
			public const int rl = 2131230729;
			
			// aapt resource value: 0x7f080010
			public const int scanAlbumBtn = 2131230736;
			
			// aapt resource value: 0x7f080013
			public const int scanBulbBtn = 2131230739;
			
			// aapt resource value: 0x7f080005
			public const int selectFold = 2131230725;
			
			// aapt resource value: 0x7f080012
			public const int textAlbum = 2131230738;
			
			// aapt resource value: 0x7f080015
			public const int textBulb = 2131230741;
			
			// aapt resource value: 0x7f08000e
			public const int textview = 2131230734;
			
			// aapt resource value: 0x7f08000a
			public const int thumbnail = 2131230730;
			
			// aapt resource value: 0x7f080000
			public const int top_layout = 2131230720;
			
			// aapt resource value: 0x7f08000f
			public const int webView = 2131230735;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ImageSelect = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ImageSelect_IncludeTop = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ImageSelect_PhotoPickGridListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ImageSelect_PhotoPickListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ImageTextButton = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Scan = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ZxingOverlay = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int zxingscanneractivitylayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int zxingscannerfragmentlayout = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int l_album_name_all = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int l_album_name_camera = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int l_album_name_download = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int l_album_name_screen_shot = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int l_album_name_selected = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int l_confirm_dialog_message = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int l_confirm_dialog_title = 2131099654;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
