#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LazyWelfare.AndroidMobile.Resource", IsApplication=true)]

namespace LazyWelfare.AndroidMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::LazyWelfare.AndroidMobile.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::LazyWelfare.AndroidMobile.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::LazyWelfare.AndroidMobile.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int aml_alpha_from = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int aml_alpha_to = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int aml_duration = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int gray_9999 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int gray_f2f2 = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int transparent = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int app_back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int area_above_left = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int area_above_right = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int area_below_left = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int area_below_right = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int blue_face = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_down = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_launcher = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_launcher_round = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_left = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_ok = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_right = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_up = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int offered_backward = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int offered_channel = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int offered_cursor = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int offered_exit = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int offered_forward = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int offered_height = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int offered_menu = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int offered_mute = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int offered_next = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int offered_out = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int offered_pause = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int offered_pause2 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int offered_play = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int offered_playloop = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int offered_previous = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int offered_random = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int offered_stop = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int offered_vol = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int offered_width = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int pretty_girl = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int scan_album = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int scan_bulb = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int splash_screen = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int splashscreen = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int svg_new_back = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int svg_new_close = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int svg_new_home = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int svg_new_setting = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int svg_new_source = 2130837545;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000c
			public const int contentFrame = 2131165196;
			
			// aapt resource value: 0x7f070001
			public const int context_Title = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int context_btback = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int imageAlbum = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int imageBulb = 2131165194;
			
			// aapt resource value: 0x7f070002
			public const int imgview = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int scanAlbumBtn = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int scanBulbBtn = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int textAlbum = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int textBulb = 2131165195;
			
			// aapt resource value: 0x7f070003
			public const int textview = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int top_layout = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int webView = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int App_IncludeTop = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ImageTextButton = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ZxingOverlay = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int zxingscanneractivitylayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int zxingscannerfragmentlayout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AlphaMaskLayout = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int AlphaMaskLayout_aml_alpha_from = 0;
			
			// aapt resource value: 1
			public const int AlphaMaskLayout_aml_alpha_to = 1;
			
			// aapt resource value: 2
			public const int AlphaMaskLayout_aml_duration = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
