#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LazyWelfare.AndroidMobile.QrcodeScan.Resource", IsApplication=false)]

namespace LazyWelfare.AndroidMobile.QrcodeScan
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int area_above_left = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int area_above_right = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int area_below_left = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int area_below_right = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int scan_album = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int scan_bulb = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public static int contentFrame = 2131034118;
			
			// aapt resource value: 0x7f050001
			public static int imageAlbum = 2131034113;
			
			// aapt resource value: 0x7f050004
			public static int imageBulb = 2131034116;
			
			// aapt resource value: 0x7f050000
			public static int scanAlbumBtn = 2131034112;
			
			// aapt resource value: 0x7f050003
			public static int scanBulbBtn = 2131034115;
			
			// aapt resource value: 0x7f050002
			public static int textAlbum = 2131034114;
			
			// aapt resource value: 0x7f050005
			public static int textBulb = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int ZxingOverlay = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int zxingscanneractivitylayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int zxingscannerfragmentlayout = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public static int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
