#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LazyWelfare.AndroidAreaView.Resource", IsApplication=false)]

namespace LazyWelfare.AndroidAreaView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public static int gray_9999 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int gray_f2f2 = 2130968579;
			
			// aapt resource value: 0x7f040001
			public static int top_bg = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int transparent = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int ic_launcher_round = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int offered_backward = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int offered_channel = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int offered_cursor = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int offered_exit = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int offered_forward = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int offered_height = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int offered_menu = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int offered_mute = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int offered_next = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int offered_out = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int offered_pause = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int offered_pause2 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int offered_play = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int offered_playloop = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int offered_previous = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int offered_random = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int offered_stop = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int offered_vol = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int offered_width = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int shape_button = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int svg_new_back = 2130837526;
			
			// aapt resource value: 0x7f020017
			public static int svg_new_close = 2130837527;
			
			// aapt resource value: 0x7f020018
			public static int svg_new_home = 2130837528;
			
			// aapt resource value: 0x7f020019
			public static int svg_new_setting = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public static int svg_new_source = 2130837530;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public static int imageCtrl = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int imageCtrl_Exit = 2131034114;
			
			// aapt resource value: 0x7f050000
			public static int top_layout = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int ImageCtrl = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int ImageCtrl_Top = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
