#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MicroBluer.AndroidCtrls.ImageExpleror.Resource", IsApplication=false)]

namespace MicroBluer.AndroidCtrls.ImageExpleror
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public static int listview_down = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int listview_fade_in = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int listview_fade_out = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int listview_up = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public static int colorAccent = 2131034114;
			
			// aapt resource value: 0x7f050000
			public static int colorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int colorPrimaryDark = 2131034113;
			
			// aapt resource value: 0x7f050003
			public static int top_bg = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int gallery_back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int gallery_down = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int gallery_up = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int ic_camera = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int image_not_exist = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int pick_photo_checkbox = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int pick_photo_checkbox_check = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int pick_photo_checkbox_normal = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public static int btn_back = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public static int check = 2131165195;
			
			// aapt resource value: 0x7f070008
			public static int commit = 2131165192;
			
			// aapt resource value: 0x7f070006
			public static int foldName = 2131165190;
			
			// aapt resource value: 0x7f070007
			public static int gallery_tip = 2131165191;
			
			// aapt resource value: 0x7f070001
			public static int gridView = 2131165185;
			
			// aapt resource value: 0x7f070003
			public static int listView = 2131165187;
			
			// aapt resource value: 0x7f070002
			public static int listViewParent = 2131165186;
			
			// aapt resource value: 0x7f07000c
			public static int photoCount = 2131165196;
			
			// aapt resource value: 0x7f070009
			public static int rl = 2131165193;
			
			// aapt resource value: 0x7f070005
			public static int selectFold = 2131165189;
			
			// aapt resource value: 0x7f07000a
			public static int thumbnail = 2131165194;
			
			// aapt resource value: 0x7f070000
			public static int top_layout = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int ImageSelect = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int ImageSelect_IncludeTop = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int ImageSelect_PhotoPickGridListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int ImageSelect_PhotoPickListItem = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public static int app_name = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int l_album_name_all = 2131099649;
			
			// aapt resource value: 0x7f060003
			public static int l_album_name_camera = 2131099651;
			
			// aapt resource value: 0x7f060004
			public static int l_album_name_download = 2131099652;
			
			// aapt resource value: 0x7f060005
			public static int l_album_name_screen_shot = 2131099653;
			
			// aapt resource value: 0x7f060002
			public static int l_album_name_selected = 2131099650;
			
			// aapt resource value: 0x7f060007
			public static int l_confirm_dialog_message = 2131099655;
			
			// aapt resource value: 0x7f060006
			public static int l_confirm_dialog_title = 2131099654;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
